export const gridTemplateLargeScreens = `
  "control                  spendingSummary     spendingSummary         breakdown"
  "control                  spendingSummary     spendingSummary         breakdown"
  "cumulSpending            cumulSpending       categoryPie             breakdown"
  "cumulSpending            cumulSpending       categoryPie             breakdown"
  "cumulSpending            cumulSpending       categoryPie             breakdown"
  "cumulSpending            cumulSpending       categoryPie             breakdown"
  "recentTransactions       recentTransactions  recentTransactions      breakdown"
  "recentTransactions       recentTransactions  recentTransactions      breakdown"
`
export const gridTemplateSmallScreens = `
  "a"
  "a"
  "a"
  "a"
  "b"
  "b"
  "b"
  "b"
  "c"
  "c"
  "c"
  "d"
  "d"
  "d"
  "e"
  "e"
  "f"
  "f"
  "f"
  "g"
  "g"
  "g"
  "h"
  "h"
  "h"
  "h"
  "i"
  "i"
  "j"
  "j"
`
