"""moved transaction type to category instead of transactions

Revision ID: 7a21ad4584e8
Revises: 1da6b0dbd358
Create Date: 2024-01-24 22:22:51.218307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a21ad4584e8'
down_revision: Union[str, None] = '1da6b0dbd358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('transaction_type', sa.String(length=50), nullable=False))
    op.add_column('category', sa.Column('transaction_subtype', sa.String(length=50), nullable=True))
    op.drop_column('category', 'category_subtype')
    op.drop_column('category', 'category_type')
    op.drop_column('transaction', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('category', sa.Column('category_type', sa.VARCHAR(length=50), nullable=False))
    op.add_column('category', sa.Column('category_subtype', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('category', 'transaction_subtype')
    op.drop_column('category', 'transaction_type')
    # ### end Alembic commands ###
