"""added category types and subtypes columns

Revision ID: e65204eb0a8a
Revises: dd716b286141
Create Date: 2024-01-24 20:58:19.135394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65204eb0a8a'
down_revision: Union[str, None] = 'dd716b286141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_type', sa.String(length=50), nullable=False))
    op.add_column('category', sa.Column('category_subtype', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_subtype')
    op.drop_column('category', 'category_type')
    # ### end Alembic commands ###
