"""Make transaction type nullable.

Revision ID: fc42d2fb256e
Revises: f7f507439404
Create Date: 2024-04-20 10:16:37.876060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc42d2fb256e"
down_revision: Union[str, None] = "f7f507439404"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("budget")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "transaction_type", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.alter_column(
            "transaction_type", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    op.create_table(
        "budget",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.Column("start_date", sa.DATETIME(), nullable=False),
        sa.Column("end_date", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
